sudo: required
services:
  - docker

before_install:
  - docker build -t guilhermecl93/react-test -f ./client/Dockerfile.dev
    
script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t guilhermecl93/multi-client ./client
  - docker build -t guilhermecl93/multi-nginx ./nginx
  - docker build -t guilhermecl93/multi-server ./server
  - docker build -t guilhermecl93/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  - docker push guilhermecl93/multi-client
  - docker push guilhermecl93/multi-nginx
  - docker push guilhermecl93/multi-server
  - docker push guilhermecl93/multi-worker